server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart?useUnicode=true&serverTimezone=UTC
    username: mekhrat
    password: Chelsea.02
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true



logging:
  file:
    name: logs/server.log

emailLogin: ClientBot.UZ.22@gmail.com
emailPassword: ueglggcxarflfcnn
